@startuml
title Object Diagram

object "startApp : StartApp" as startApp

object "simulationPanel : SimulationPanel" as simulationPanel {
  world = world
  isPaused = false
}

object "world : World" as world {
  grid = [[null, null, null], [null, null, null], [null, null, null]]
  animals = [pred1, prey1, prey2]
  turns = 10
}

object "pred1 : Predator" as pred1 {
  position = (2, 3)
  energy = 50
  age = 3
  maxAge = 15
}

object "prey1 : Prey" as prey1 {
  position = (4, 5)
  energy = 40
  age = 2
  maxAge = 10
}

object "prey2 : Prey" as prey2 {
  position = (1, 2)
  energy = 30
  age = 1
  maxAge = 8
}

' Relacje (zależności przez pola)
startApp -- simulationPanel : contains
simulationPanel -- world : manages
world "contains" -- pred1
world "contains" -- prey1
world "contains" -- prey2

@enduml