name: Run Maven Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven and run tests
        run: mvn clean verify

      - name: Upload JaCoCo test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Upload Surefire test reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload Surefire HTML test reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-html-reports
          path: target/reports/

      - name: Publish test summary
        run: |
          if ls target/surefire-reports/TEST-*.xml 1> /dev/null 2>&1; then
            echo "Test results found, publishing summary."
            echo "## Test Results" >> $GITHUB_STEP_SUMMARY
            for file in target/surefire-reports/*.txt; do
              echo "\`\`\`text" >> $GITHUB_STEP_SUMMARY
              cat "$file" >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
            done
            echo "Test summary published."
          else
            echo "No test results found, skipping summary publication."
          fi
